import Link from "next/link";

export default function WhatIs() {
  return (
    <div className="max-w-[720px] mx-auto px-6 py-16">
      <h1 className="text-4xl font-extrabold mb-4">What Is Neuroplastic Pain?</h1>
      <p className="text-lg text-text-muted max-w-[650px] mb-8 leading-relaxed">
        <strong>Neuroplastic pain</strong> (also called <em>nociplastic pain</em>, <em>Mind Body Syndrome</em>,
        or <em>Tension Myoneural Syndrome</em>) is real physical pain generated by learned neural
        pathways in the brain — not by ongoing tissue damage or structural problems. It is the most
        common form of chronic pain.
      </p>

      <div className="rounded-xl p-6 bg-teal-light/70 dark:bg-teal/10 border border-teal dark:border-teal/30 mb-8">
        <p className="font-bold text-lg mb-1">Key insight</p>
        <p className="m-0 leading-relaxed">
          Pain is a <strong>danger signal</strong> produced by the brain. Normally it alerts us to tissue
          damage. But in neuroplastic pain, the brain <em>misfires</em> — generating pain in the absence
          of injury. The pain is 100% real. Brain imaging (fMRI) shows the same pain centers activate
          as with physical injury. The difference is not in how it <em>feels</em> but in what <em>causes</em> it.
        </p>
      </div>

      <h2 className="text-2xl font-bold mt-10 mb-4">The Evolution of Understanding</h2>
      <p className="mb-6">This concept isn&apos;t new — it has a decades-long history of clinical observation and research validation:</p>

      <div className="space-y-4 mb-8">
        {[
          {
            year: "1970s",
            person: "Dr. John E. Sarno",
            desc: "A rehabilitation medicine physician at NYU, Sarno observed that many chronic pain patients had no detectable structural cause. He named it Tension Myoneural Syndrome (TMS) and proposed that repressed emotions — particularly rage — created physical pain by reducing blood flow to muscles and nerves. His books (including Healing Back Pain) helped thousands recover, often in weeks."
          },
          {
            year: "2000s-Present",
            person: "Dr. Howard Schubiner",
            desc: "An internist and professor, Schubiner trained directly with Sarno and expanded his work with modern neuroscience. He renamed the condition Mind Body Syndrome (MBS) and published the Unlearn Your Pain workbook — a step-by-step program combining neuroscience education, emotional awareness work, and behavioral techniques."
          },
          {
            year: "2021",
            person: "Alan Gordon & Pain Reprocessing Therapy",
            desc: "Gordon, a psychotherapist who recovered from his own chronic pain, developed Pain Reprocessing Therapy (PRT). A landmark RCT in JAMA Psychiatry showed 66% of chronic back pain patients became pain-free or nearly pain-free after just 8 sessions over 4 weeks. Gordon's book The Way Out became a NYT bestseller."
          },
          {
            year: "2026",
            person: "Mainstream Acceptance",
            desc: "Schubiner's new book was published by Penguin/Random House. The documentary This Might Hurt brought mind-body medicine to wider audiences. The Association for the Treatment of Neuroplastic Symptoms (ATNS) now trains practitioners worldwide. Neuroplastic pain is no longer fringe — it's evidence-based mainstream medicine."
          },
        ].map((item, i) => (
          <div key={i} className="rounded-xl p-5 bg-white dark:bg-zinc-900 border border-border dark:border-zinc-800 border-l-4 border-l-teal shadow-sm">
            <h3 className="text-base font-bold mb-1">{item.person} ({item.year})</h3>
            <p className="text-sm text-text-muted m-0">{item.desc}</p>
          </div>
        ))}
      </div>

      <h2 className="text-2xl font-bold mt-10 mb-4">What&apos;s actually happening?</h2>
      <p className="mb-4">You may have heard the term <strong>predictive processing</strong>. Here&apos;s what it means in plain language:</p>
      <p className="mb-4">
        Your brain doesn&apos;t passively receive sensations from your body — it actively <em>constructs</em>
        your experience. Based on past experiences, current context, and your emotional state, your brain
        makes predictions about what&apos;s happening and generates the corresponding experience.
      </p>

      <div className="rounded-xl p-6 bg-white dark:bg-zinc-900 border border-border dark:border-zinc-800 border-t-3 border-t-teal shadow-sm mb-8">
        <h3 className="text-lg font-bold mt-0 mb-3">The Predict-Compare-Update cycle</h3>
        <ol className="mb-0 leading-relaxed space-y-2">
          <li><strong>Predict:</strong> Your brain constantly predicts what sensations are coming based on memory</li>
          <li><strong>Compare:</strong> It compares predictions against actual sensory input</li>
          <li><strong>Update:</strong> If there&apos;s a mismatch, it can update the prediction — or override the input</li>
        </ol>
        <p className="text-sm text-text-muted mt-3 m-0">
          With chronic pain, your brain&apos;s predictions have become <strong>biased toward danger</strong>.
          It overrides safe sensory input with a pain prediction. You feel real pain — but it&apos;s being
          generated by faulty predictions, not by tissue damage.
        </p>
      </div>

      <h2 className="text-2xl font-bold mt-10 mb-4">How does the brain learn pain?</h2>
      <p className="mb-4">
        The same <strong>neuroplasticity</strong> that lets you learn guitar or a language
        also lets your brain learn pain. When pain persists, the neural connections become
        <strong>reinforced</strong> — like a path through a forest that gets wider the more it&apos;s walked.
      </p>
      <ul className="list-disc pl-5 mb-6 space-y-1">
        <li>Pain pathways strengthen — neurons that fire together wire together</li>
        <li>Pain inhibition weakens — the brain&apos;s natural pain-control system stops working properly</li>
        <li>Emotion and pain circuits link up — fear, anxiety, and stress directly amplify pain signals</li>
        <li>Glial cells release inflammatory molecules that maintain the sensitized state</li>
        <li>Body maps in the brain distort — the somatosensory cortex can blur or shrink</li>
      </ul>

      <h2 className="text-2xl font-bold mt-10 mb-4">Why you — specifically?</h2>
      <p className="mb-4">Neuroplastic pain often develops in people with certain traits — not because those traits are bad, but because they lead to a buildup of unexpressed emotional stress:</p>

      <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3 mb-6">
        {[
          { trait: "Perfectionism", desc: "Setting impossibly high standards for yourself" },
          { trait: "People-pleasing", desc: "Difficulty saying no, prioritizing others" },
          { trait: "Conscientiousness", desc: "Strong sense of duty and responsibility" },
          { trait: "High anxiety", desc: "Worry and vigilance that trigger the stress response" },
          { trait: "Self-criticism", desc: "An inner voice that's harsh and unforgiving" },
          { trait: "Childhood adversity", desc: "Early experiences that shaped threat sensitivity" },
        ].map((item, i) => (
          <div key={i} className="rounded-xl p-4 bg-white dark:bg-zinc-900 border border-border dark:border-zinc-800 shadow-sm">
            <strong>{item.trait}</strong>
            <p className="text-xs text-text-muted mt-0.5 m-0">{item.desc}</p>
          </div>
        ))}
      </div>

      <div className="rounded-xl p-5 bg-amber-50 dark:bg-amber-950/30 border border-amber-200 dark:border-amber-800 mb-8">
        <p className="text-sm m-0">
          <strong>This doesn&apos;t mean the pain is your fault.</strong> It means your brain learned
          a protective pattern — likely in response to real stressors — and that pattern kept running
          even when it was no longer helpful. The good news: you can teach it a new one.
        </p>
      </div>

      <h2 className="text-2xl font-bold mt-10 mb-4">Is your pain neuroplastic?</h2>
      <p className="mb-4">Key indicators that your pain may have a neuroplastic component:</p>
      <ul className="list-disc pl-5 mb-8 space-y-1">
        <li>It persists long after an injury should have healed</li>
        <li>It moves or spreads to different body parts</li>
        <li>Multiple body systems are affected (pain + fatigue + gut issues)</li>
        <li>Stress makes it significantly worse</li>
        <li>Treatments targeting the body haven&apos;t helped — or made things worse</li>
        <li>Medical tests come back normal or show &ldquo;age-appropriate&rdquo; changes</li>
        <li>It began during or after a stressful period in your life</li>
        <li>You have symmetrical symptoms (both sides of the body)</li>
        <li>Pain has triggers unrelated to the body (weather, sounds, smells, time of day)</li>
        <li>Pain has a delayed onset after activity rather than immediate</li>
      </ul>

      <div className="rounded-xl p-6 bg-gradient-to-br from-teal-light to-teal-light/50 dark:from-teal/10 dark:to-teal/5 border border-teal dark:border-teal/30 mb-8">
        <p className="text-lg font-semibold leading-relaxed m-0">
          <strong>Your pain is real. It can also change.</strong> The brain that learned pain can learn
          safety. Neuroplasticity — the same process that locked in the pain — is the very mechanism
          that allows recovery.
        </p>
      </div>

      <div className="flex gap-3 flex-wrap">
        <Link href="/intro/science" className="inline-flex items-center px-5 py-2.5 rounded-lg bg-teal text-white font-semibold hover:bg-teal-dark transition">Next: The Science &rarr;</Link>
        <Link href="/intro/symptoms" className="inline-flex items-center px-5 py-2.5 rounded-lg border-2 border-teal text-teal font-semibold hover:bg-teal-light transition">Common Symptoms</Link>
        <Link href="/quiz" className="inline-flex items-center px-5 py-2.5 rounded-lg border border-border dark:border-zinc-700 text-text-muted font-semibold hover:bg-border-light dark:hover:bg-zinc-800 transition">Take the Quiz</Link>
      </div>
    </div>
  );
}
