import Link from "next/link";

export default function PRT() {
  return (
    <div className="max-w-[720px] mx-auto px-6 py-16">
      <h1 className="text-4xl font-extrabold mb-2">Pain Reprocessing Therapy (PRT)</h1>
      <p className="text-text-muted text-lg max-w-[650px] mb-6">
        A step-by-step protocol developed by Alan Gordon, LCSW. PRT retrains the brain to reinterpret pain signals as safe — breaking the chronic pain cycle at its source.
      </p>

      <div className="rounded-xl p-5 bg-gradient-to-br from-teal-light to-teal-light/50 dark:from-teal/10 dark:to-teal/5 border border-teal dark:border-teal/30 mb-10">
        <p className="text-base m-0 font-semibold">
          Research: RCT in JAMA Psychiatry (2021) — 66% pain-free after 4 weeks, 98% improved. Results maintained at 5-year follow-up.{" "}
          <a href="https://jamanetwork.com/journals/jamapsychiatry/fullarticle/2784694" target="_blank" rel="noopener noreferrer" className="text-teal hover:underline">Read the study &rarr;</a>
        </p>
      </div>

      <h2 className="text-2xl font-bold mb-8">The Five Components of PRT</h2>

      {[
        {
          num: 1,
          title: "Education: Understanding the brain origins of pain",
          body: (
            <>
              <p>The first step is cognitive: learn why your pain persists. Understanding that chronic pain can be generated by the brain — not by tissue damage — is itself therapeutic (Pain Neuroscience Education).</p>
              <ul className="list-disc pl-5 space-y-1">
                <li>Pain is a danger signal produced by the brain, not a direct readout of body damage</li>
                <li>The brain can learn to generate pain even when tissues are healthy</li>
                <li>Neuroplasticity means the brain can change — both to learn and unlearn pain</li>
                <li>Your pain is 100% real — you're not "making it up"</li>
                <li>Understanding this reduces fear, which is the first step to recovery</li>
              </ul>
            </>
          ),
        },
        {
          num: 2,
          title: "Gathering personalized evidence",
          body: (
            <>
              <p>Build genuine conviction that <em>your</em> pain is neuroplastic. Collect evidence:</p>
              <ul className="list-disc pl-5 space-y-1">
                <li>Did your pain begin during a period of stress?</li>
                <li>Does pain move or spread unpredictably?</li>
                <li>Are symptoms inconsistent — good days and bad days?</li>
                <li>Do you have multiple symptoms in different body systems?</li>
                <li>Have structural treatments not helped?</li>
                <li>Does stress make it worse? Do enjoyable activities make it better?</li>
              </ul>
              <p className="text-sm text-text-muted"><strong>Tip:</strong> Write these down. Create a list you can revisit when doubt creeps in. Bulging discs and "degeneration" are normal age-related findings in pain-free people.</p>
            </>
          ),
        },
        {
          num: 3,
          title: "Somatic Tracking: the core technique",
          body: (
            <>
              <p>This is where the real neural rewiring happens. Somatic tracking involves attending to pain sensations with <strong>curiosity and safety</strong> rather than fear and resistance.</p>
              <div className="rounded-lg p-5 bg-white dark:bg-zinc-900 border border-border dark:border-zinc-800 border-l-4 border-l-teal shadow-sm my-4">
                <h4 className="text-base font-bold mt-0 mb-3">How to do somatic tracking</h4>
                <ol className="list-decimal pl-5 m-0 space-y-1.5 text-sm text-text-muted">
                  <li><strong className="text-text dark:text-zinc-100">Find the sensation.</strong> Notice where the pain is. Don't resist it — acknowledge it.</li>
                  <li><strong className="text-text dark:text-zinc-100">Observe with curiosity.</strong> What does it actually feel like? Hot? Tight? Pulsing? Get descriptive, not judgmental.</li>
                  <li><strong className="text-text dark:text-zinc-100">Send messages of safety.</strong> "This sensation is safe. There is no danger. My body is okay."</li>
                  <li><strong className="text-text dark:text-zinc-100">Don't try to make it go away.</strong> Accepting the sensation's presence while reinforcing safety paradoxically allows it to fade.</li>
                  <li><strong className="text-text dark:text-zinc-100">Shift attention gently.</strong> Broadly include the room, sounds, breathing. Return to the sensation occasionally with curiosity.</li>
                  <li><strong className="text-text dark:text-zinc-100">Repeat.</strong> Practice multiple times per day. Each time you face pain with safety, the neural pathway weakens.</li>
                </ol>
              </div>
              <div className="rounded-lg p-4 bg-amber-50 dark:bg-amber-950/30 border border-amber-200 dark:border-amber-800">
                <h4 className="text-base font-bold mt-0 mb-2">Common mistakes</h4>
                <ul className="list-disc pl-5 m-0 text-sm space-y-1">
                  <li><strong>Using somatic tracking to "fix" pain</strong> — the goal is to experience sensation safely, not make it disappear.</li>
                  <li><strong>Frustration when pain doesn't change</strong> — sometimes nothing happens in the moment. Rewiring happens over time.</li>
                  <li><strong>Bracing against the sensation</strong> — tension and resistance tell the brain there's danger. Soften around the pain.</li>
                </ul>
              </div>
            </>
          ),
        },
        {
          num: 4,
          title: "Addressing emotional threats",
          body: (
            <ul className="list-disc pl-5 space-y-1">
              <li><strong>Identify patterns:</strong> When pain spikes, ask: "What was I feeling right before?"</li>
              <li><strong>Allow and process:</strong> Give yourself permission to feel the emotion without judgment.</li>
              <li><strong>Challenge self-criticism:</strong> The inner critic is a major pain amplifier. Practice self-compassion.</li>
              <li><strong>Set boundaries:</strong> People-pleasing and over-giving create internal pressure.</li>
              <li><strong>Process trauma:</strong> If there is a history of trauma, consider working with a trauma-informed PRT practitioner.</li>
            </ul>
          ),
        },
        {
          num: 5,
          title: "Gravitating toward positive feelings",
          body: (
            <ul className="list-disc pl-5 space-y-1">
              <li><strong>Do things you enjoy</strong> — even when you don't feel like it. Joy sends safety signals.</li>
              <li><strong>Connect with people</strong> — social connection is a strong antidote to threat physiology.</li>
              <li><strong>Practice gratitude</strong> — not as toxic positivity, but as genuine noticing of what's good.</li>
              <li><strong>Engage in meaningful activity</strong> — purpose and meaning activate resilience circuits.</li>
              <li><strong>Move your body gently</strong> — gradually reintroduce activities you've been avoiding.</li>
            </ul>
          ),
        },
      ].map((comp) => (
        <section key={comp.num} className="mb-10">
          <div className="flex items-center gap-3 mb-3">
            <div className="w-9 h-9 rounded-full bg-teal text-white flex items-center justify-center font-bold flex-shrink-0">{comp.num}</div>
            <h3 className="text-lg font-bold m-0">{comp.title}</h3>
          </div>
          <div className="text-text-muted leading-relaxed space-y-3">{comp.body}</div>
        </section>
      ))}

      <h2 className="text-2xl font-bold mt-12 mb-4">What to expect during PRT recovery</h2>
      <ul className="list-disc pl-5 mb-8 space-y-2">
        <li><strong>Weeks 1-2:</strong> Education phase. Learning often brings immediate relief — your brain starts updating its danger assessment.</li>
        <li><strong>Weeks 2-4:</strong> Active rewiring. Daily somatic tracking. Pain may fluctuate — this is normal. The brain is testing whether it's safe.</li>
        <li><strong>Weeks 4-8:</strong> Consolidation. Pain often reduces significantly. Emotional processing deepens. Old triggers lose power.</li>
        <li><strong>Months 2-6:</strong> Integration. New neural patterns stabilize. Occasional flares are shorter and respond quickly.</li>
      </ul>

      <div className="rounded-xl p-5 bg-teal-light/70 dark:bg-teal/10 border border-transparent mb-8">
        <p className="text-sm m-0">
          <strong>When to seek help:</strong> While many people recover using Alan Gordon's book <em>The Way Out</em>, PRT is most effective with a trained practitioner. The PRT practitioner directory lists certified providers. Group workshops are also available and more affordable.
        </p>
      </div>

      <div className="flex gap-3 flex-wrap">
        <Link href="/intro/treatments" className="inline-flex items-center px-5 py-2.5 rounded-lg bg-teal text-white font-semibold hover:bg-teal-dark transition">All Treatments &rarr;</Link>
        <Link href="/protocols/schubiner" className="inline-flex items-center px-5 py-2.5 rounded-lg border-2 border-teal text-teal font-semibold hover:bg-teal-light transition">Schubiner's Method</Link>
        <Link href="/resources" className="inline-flex items-center px-5 py-2.5 rounded-lg border border-border dark:border-zinc-700 text-text-muted font-semibold hover:bg-border-light dark:hover:bg-zinc-800 transition">Resources</Link>
      </div>
    </div>
  );
}
